checks:
    java: true

filter:
    excluded_paths:
        - test/*

build:
    environment:
        sdkman:
            - java@9.0.0-zulu
            - maven

    tests:
        override:
            -
                command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent test
                coverage:
                    file: "target"
                    format: "jacoco"
